### ISSUE TITLE
[iOS][Android] Career Center reminder pls set default at next day

### ISSUE THREAD

**Issue by christyyeung** [USThing/USThing_Master#10]
### App Version and device
Android

### Expected behavior
Set a reminder about job deadline well ahead of the actual deadline, so default at next day seems more reasonable.  

### Actual behavior
Reminder date default as job deadline.  User will probably have to miss the deadline if they're reminded so late.  So now user will have to scroll about 2 or 3 months back to set an earlier deadline.

**Comment by Camerash** [comment]
tszkanlo/USThing_Android#59
