### ISSUE TITLE
[EMS] Show message when there is no event

### ISSUE THREAD

**Issue by chihimng** [USThing/USThing_Master#101]
### Expected behavior
Display text to tell user there is no event
### Actual behavior
table view is blank, add section show spinner forever

**Comment by tszkanlo** [comment]
![simulator screen shot - iphone x - 2017-10-16 at 00 34 37](https://user-images.githubusercontent.com/1873031/31586860-e35ef622-b209-11e7-8b1c-2ba0d604eec0.png)

@christyyeung please check the wordings. and maybe we need a placeholder banner image for the banner area.

**Comment by Camerash** [comment]
Android version currently have a boring textview with text "No events" and "No joined events", should I add the fancy emoji version?

**Comment by chihimng** [comment]
implemented in iOS, removing tags

**Comment by chihimng** [comment]
implemented in android as well
