### ISSUE TITLE
Project account UX issue

### ISSUE THREAD

**Issue by Camerash** [USThing/USThing_Master#106]
### Expected behavior
The logged in project account user should be notified for "Not entitled to use function" when they click on services that arent available to project accounts (E.g.: FBS)

### Actual behavior
The user is shown "Please logged in first", which is confusing since the project account user is already logged in

*And particularly in FBS function of iOS version, project account users can actually get into FBS, but after checking whichever timeslot it always returns "No timeslots available", which is confusing

It is preferably to stop the project account users before they could get into the FBS service 

### Steps to reproduce

*Please also add the label iOS or / and Android for the issue

**Comment by bryanchun** [comment]
Can I have a look of the expected homepage for project users? Or what features are specially added for them and what are disabled?

**Comment by chihimng** [comment]
closed for now, project acc is not officially supported, for staff accounts unusable features will be filtered via user utils feat
