### ISSUE TITLE
[Grades] Semester unexpected sorting (minor)

### ISSUE THREAD

**Issue by bryanchun** [USThing/USThing_Master#109]
### Expected behaviour
The correct order should be:
- 2016-17 Summer, if the user had enrolled any course
- 2016-17 Spring
- 2016-17 Winter, if the user had enrolled any course
- 2016-17 Fall
In other words, sorted in descending order of time

### Actual behaviour
Summer comes before Fall of an academic year:

![img_20170616_131800](https://user-images.githubusercontent.com/22416129/27231337-e4e1c3be-52e4-11e7-8090-b741e95777df.jpg)

### Steps to reproduce
Open Grades of a user who (ever) enrolled in a Summer semester.
May have similar problem with Winter semester.
Expected correct sorting across academic years but if possible please also check with it.

*Please also add the label iOS or / and Android for the issue

**Comment by chihimng** [comment]
sorting is correct in raw api response, probably front-end related issue
verified that iOS has same issue

**Comment by chihimng** [comment]
on iOS, semesters are sorted by ascending order of time, agree that should be in descending order instead (i.e. newest on top)

**Comment by Camerash** [comment]
Issue fixed on tszkanlo/USThing_Android#139
