### ISSUE TITLE
[iOS] Grades view not reloaded after api request done

### ISSUE THREAD

**Issue by chihimng** [USThing/USThing_Master#113]
### Expected behavior
- table is refreshed after request finish

### Actual behavior
- empty table is shown after refresh, user has to relaunch button to see refreshed results

### Steps to reproduce
- press refresh button in semester details view (if semester already exist)
- pull to refresh in main view

*Please also add the label iOS or / and Android for the issue

**Comment by tszkanlo** [comment]
@chihimng this issue only related to 2fa user?

**Comment by chihimng** [comment]
should be affecting all users... issue most significant in semester detail page, table is empty after refreshing via nav bar button

**Comment by chihimng** [comment]
fixed in 4.03
