### ISSUE TITLE
[iOS] crash when navigating from First Year Info to Homepage

### ISSUE THREAD

**Issue by chihimng** [USThing/USThing_Master#114]
### Expected behavior
- should be fixed by disabling navbar user interaction during magical record access

### Actual behavior
- app crashes

### Steps to reproduce
- refresh checklist, press back button immediately

*Please also add the label iOS or / and Android for the issue

**Comment by chihimng** [comment]
should be fixed after revamping info card save and fetch flow, tests should be done to validate whole info card feature tho

**Comment by tszkanlo** [comment]
thanks!
