### ISSUE TITLE
[iOS] EMS infinite loading

### ISSUE THREAD

**Issue by chihimng** [USThing/USThing_Master#116]
### Expected behavior
- Should stop progress hud and display error if timeout

### Actual behavior
- ui is locked by progress hud after api error

### Steps to reproduce
- occurs with certain accounts which accessed older versions of the app

*Please also add the label iOS or / and Android for the issue

**Comment by tszkanlo** [comment]
Solved by resetting user password (lambda function on skygear cloud code)
