### ISSUE TITLE
[TimeMatch] Display simple description on first feature launch

### ISSUE THREAD

**Issue by chihimng** [USThing/USThing_Master#120]
### Expected behavior
Explain to user what this feature is for
### Actual behavior
No explanation is given, only instruction to create event is shown
### Steps to reproduce
N/A
### Suggested fix
Add simple description on the feature to current message for empty list

*Please also add the label iOS or / and Android for the issue

**Comment by bryanchun** [comment]
Maybe instead of showing in feature first launch, this can become the general placeholder when the users don't have matches, for example when after a semester cleanup or manually deleted all or never added any.

**Comment by chihimng** [comment]
@bryanchun that's exactly what we are doing
