### ISSUE TITLE
[iOS][Android] About page add content team name

### ISSUE THREAD

**Issue by tszkanlo** [USThing/USThing_Master#125]
Add the following members name
Content team:
Karen Lam
Carmen Lui
Irene Yu
Wendy Wong

**Comment by tszkanlo** [comment]
Marvis Ng
Kevin Cao

**Comment by chihimng** [comment]
store the list on restdb?

**Comment by tszkanlo** [comment]
Sure

**Comment by chihimng** [comment]
added credits table in internal restdb, @Camerash or @c-samuel can you help add android ppl?

**Comment by chihimng** [comment]
iOS Screenshot, Content obtained from restdb
![simulator screen shot - iphone 7 ios 10 - 2017-09-04 at 21 07 24](https://user-images.githubusercontent.com/11769136/30027836-21a86ef6-91b5-11e7-87dd-e81fc5809677.png)

**Comment by chihimng** [comment]
btw should we change christy's title as content? ~or consultant~
