### ISSUE TITLE
[iOS] FBS inconvenience when encountering 'Time slot not available' error

### ISSUE THREAD

**Issue by mcreng** [USThing/USThing_Master#126]
### Expected behavior
If there is not available time slots for certain venues in FBS, users should return to the venue menu.

### Actual behavior
Users are kicked out to the main menu instead.

### Steps to reproduce
1. Go to 'FBS'
2. Enter Captcha 
3. Select a venue & date/time with unavailable timeslot
4. Click 'OK' for the error 'Time slot not available'
5. User being kicked out to main menu

(the following is another minor bug that follows this inconvenience UX)

6. Go to 'FBS' again
7. When asks for Captcha, Captcha does not display correctly.

### Issue seen on
* iPhone, iOS 10.3.3, app version 4.03
* iPad, iOS 10.3.3, app version 4.03

Keep up the good work guys.

**Comment by chihimng** [comment]
@mcreng Thank you for the bug report. This issue will be fixed in next release (v4.04).
