### ISSUE TITLE
[iOS] Unexpected mandatory input of telephone number in user profile

### ISSUE THREAD

**Issue by mcreng** [USThing/USThing_Master#127]
### Expected behavior
Either

* Users should be asked for their phone numbers as app starts if USThing requires so

or 

* Users should be allowed to exit the edit screen of user profile with empty phone number 

### Actual behavior
Users are stuck in the edit screen of user profile if they have empty phone number. The app needs to be killed then.

### Steps to reproduce
1. Go to settings at top right corner
2. Select 'Edit Profile'

### Issue seen on
* iPhone, iOS 10.3.3, app version 4.03
* iPad, iOS 10.3.3, app version 4.03

Keep up the good work guys.

**Comment by chihimng** [comment]
@mcreng Thank you for your feedback. This behavior is part of the flow of Events feature, where phone number is required for registration. We are revising that flow and users would be allowed to leave Profile page. This change will be implemented in next version (v4.04).
