### ISSUE TITLE
[iOS] Users unable to toggle 'Next Lesson' notification setting

### ISSUE THREAD

**Issue by mcreng** [USThing/USThing_Master#136]
### Expected behavior
Users should be able to turn off the notification of 'Next Lesson' in settings.

### Actual behavior
Users could not do so. It seems the setting is not saved upon toggle.

### Steps to reproduce
1. Go to settings
2. Toggle 'Next Lesson'
3. Leave the settings
4. Re-enter the settings, the setting was not saved.

### Issue seen on
* iPhone, iOS 10.3.3, app version 4.04
* iPad, iOS 10.3.3, app version 4.04

Keep up the good work guys.

**Comment by chihimng** [comment]
Issue verified and fixed. Scheduled to roll out in next release v4.05.

**Comment by chihimng** [comment]
Changes rolled out in v4.05
