### ISSUE TITLE
[iOS][minor] CGA Goal Seek invalid I/O issues

### ISSUE THREAD

**Issue by mcreng** [USThing/USThing_Master#137]
It'd probably be a better practice to show warning messages if the user input/CGA goal seek result falls beyond the range of CGA [0, 4.30]. You may consider implementing this but it is fine otherwise as well. Keep up the good work.

**Comment by chihimng** [comment]
Suggestion implemented and will be rolled out in next release v4.05. Thank you for your feedback :)

**Comment by chihimng** [comment]
Changes rolled out in v4.05
