### ISSUE TITLE
When sharing timematch result, weekday no. should always be in English

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#144]
### Expected behavior
When sharing timematch result, weekday no. should always be in English 
e.g. Friday, Monday
### Actual behavior
Showing weekday no. according to phone language
### Steps to reproduce
1. in a timematch that has >1 participants, click 'share' button
2. click 'share result' 
3. choose whatsapp (or any other)
4. choose a recipient
5. view in whatsapp
### Issue seen in
iPhone 6 iOS 10.2.1
### Remarks
This issue is significant because international students can't read chinese
### screencap
![image](https://user-images.githubusercontent.com/27733996/31379524-0b90fbc2-ade1-11e7-84a1-d2a670a55c58.png)

**Comment by chihimng** [comment]
this is supposedly related to date formatter locale settings, and would be painful to fix... and seems ios 11 would change that behavior (use app locale setting instead of user's) ref: https://stackoverflow.com/questions/46205763/nsdateformatter-and-current-language-in-ios11

**Comment by chihimng** [comment]
fixed all date formatter issues in iOS v4.20
