### ISSUE TITLE
When sharing timematch QR code or result, the prompted link content should not be 'DOCKER CLOUD' and 'Hello World'

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#145]
### Expected behavior
When scanning timematch QR code using code scanning apps, or sharing result to other apps like whatsapp, show link content as:
'[Event Name] TimeMatch Results' (Title)
'Please open this page with USThing app to view the timetable matching results.' (Content)
### Actual behavior
When scanning timematch QR code using code scanning apps, or sharing result to other apps like whatsapp, the link content is as belows:
![image](https://user-images.githubusercontent.com/27733996/31384544-024df630-adf2-11e7-9b47-d969868ae20d.png)
### Steps to reproduce
1. in a timematch that has >1 participants, click 'share' button
2. click 'share result' 
3. choose whatsapp 
4. choose a recipient
5. view in whatsapp, link title is shown as 'Hello World'
or
1. scan a QR code on other code scanning app
2. open the link in browser
3. a website that looks like the screenshot above is shown

**Comment by chihimng** [comment]
should be server issue, changing tags

**Comment by chihimng** [comment]
should be fixed, thanks @IniZio
