### ISSUE TITLE
(New booking) After changing time/date without clicking "search" then change location/size filter, results below show strange grey colors

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#148]
### Expected behavior
Don't refresh the results after changing location/size filter
### Actual behavior
results shown have some all dark grey/light grey results
![image](https://user-images.githubusercontent.com/27733996/31576004-1e557e44-b125-11e7-8770-df27fc3a98c1.png)

### Steps to reproduce
1. enter new booking
2. change the date/time
3. don't click 'search'
4. change a location/room size filter
5. view the results below (some are dark grey, some are light grey)
![image](https://user-images.githubusercontent.com/27733996/31575980-84ffbd18-b124-11e7-9354-6ad4826634f7.png)

### App version
ios version 4.10 (22)

**Comment by chihimng** [comment]
passed for discussion in feature team

**Comment by chihimng** [comment]
this is the expected behavior
it indicates that there's available slots after the first 6 hours, thus it's clickable and users can see all available slots within specified search parameters

this issue will be closed after the fix for showing all timeslots in confirmation page is merged
