### ISSUE TITLE
no card in homepage after making reservation in new booking

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#149]
### Expected behavior
show card of closest upcoming reservation / all upcoming reservations in homepage
### Actual behavior
No card after reservation made
### Steps to reproduce
1. enter new booking
2. make a reservation
### App Version
ios version 4.10 (22)

**Comment by Camerash** [comment]
Implemented in tszkanlo/USThing_Android#140

**Comment by chihimng** [comment]
will be fixed in ios next version
