### ISSUE TITLE
when searching whole day timeslot in new booking, maximum only showed 3 rows of timeslot

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#150]
### Expected behavior
show all timeslots as set in the searching filter
### Actual behavior
only showed a maximum of 3 rows results (4*3=12 timeslots)
### Steps to reproduce
1. enter new booking
2. search by 9am-end of day
3. click into an available room
4. view the timeslots shown
![image](https://user-images.githubusercontent.com/27733996/31581401-ab9f4ef6-b19d-11e7-9018-60b5362edd73.png)

### App Version
ios version 4.10 (22)

**Comment by chihimng** [comment]
this is actually the planned behavior, passed for discussion in feature team

**Comment by chihimng** [comment]
will be fixed in next release

**Comment by chihimng** [comment]
Fixed in v4.12
