### ISSUE TITLE
[Homepage] Cannot load homepage

### ISSUE THREAD

**Issue by bryanchun** [USThing/USThing_Master#154]
### Expected behavior
Normally open the homepage.

### Actual behavior
![whatsapp image 2017-10-30 at 12 46 07 pm](https://user-images.githubusercontent.com/22416129/32157044-f0207660-bd7b-11e7-9b43-3d16d9730811.jpeg)
This loading screen persists even after reopening the app.

### Steps to reproduce
Open the app.

*Please also add the label iOS or / and Android for the issue

**Comment by tsznokwong** [comment]
@Camerash @frankwangyufei is the issue still valid?

**Comment by frankwangyufei** [comment]
Probably not ~~hopefully~~
