### ISSUE TITLE
[Career Center] confusion with filtering and search, possible to indicate filters?

### ISSUE THREAD

**Issue by christyyeung** [USThing/USThing_Master#16]
### App Version and device 
Android

### Expected behavior
After filtering the list,  I hit the search button I expected it's a brand new search and not just displaying search from filtered results.  If I'm actively searching I might try different filters, so I'd need some kind of indication of what my current filters are so I can choose other filters.

### Actual behavior
Keep bumping into "no jobs found" because I've forgotten that I've applied filters.  Need to choose "all" in both filters every time I want to try new filter or when I want to switch to search with entering my own keywords.

**Comment by Camerash** [comment]
tszkanlo/USThing_Android#59
