### ISSUE TITLE
in Settings > About, failed to retrieve content

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#161]
### Expected behavior
show USThing member names and so?
### Actual behavior
only showing version number
### Steps to reproduce
Settings>About
### Version
ios 4.12 (25)

**Comment by chihimng** [comment]
the issue is probably related to server downtime today, please try again after the issue is resolved? (we are almost done, should be ready tmr morning the latest)

**Comment by chihimng** [comment]
issue resolved after server migration

**Comment by cindyip** [comment]
i still have this issue no matter on version 4.12(25) or 4.11(3) @chihimng

**Comment by chihimng** [comment]
@cindyip it will be fixed in next build (will be available on testflight tmr morning), cuz we have to change some config after the migration

**Comment by cindyip** [comment]
then can you tell me when will it be available for me to test again in the comment next time? thanks! @chihimng

**Comment by cindyip** [comment]
@chihimng is it supposed to be working now?

**Comment by cindyip** [comment]
sor verified now

**Comment by cindyip** [comment]
it's not working again :( @chihimng

**Comment by chihimng** [comment]
@cindyip one of our database service stopped randomly again... just restarted and will see whats wrong

**Comment by chihimng** [comment]
@cindyip i've just updated some config on server, should be auto-restarting next time... thanks
