### ISSUE TITLE
[iOS] [Booking] date picker in booking is not having effect on search results

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#164]
### Expected behavior
search results are filtered by date picker

### Actual behavior
search results are filtered by 'today'

### Steps to reproduce
1. enter booking
2. choose any facility
3. choose any date except 'today' in date picker
4. click 'search'

### Version
iOS 4.12(26) iphone 6

**Comment by chihimng** [comment]
will be fixed in next release
