### ISSUE TITLE
When clicked 'use my full name' in edit profile, 'GuestXXX' is appeared as preferred name

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#166]
### Expected behavior
show full name of the user in 'preferred name'

### Actual behavior
show 'GuestXXX' (random 3 digit no.)

### Steps to reproduce
Settings > edit profile > use my full name

### Version
ios 4.12(26) iphone6

**Comment by chihimng** [comment]
server side issue, should be fixed now

**Comment by cindyip** [comment]
bugfix verified
