### ISSUE TITLE
[iOS] after closing CGA goal seek dialog, numeric keyboard appears again 

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#167]
### Expected behavior
after closing 'OK', CGA goal seek dialog closes

### Actual behavior
after closing 'OK', CGA goal seek dialog closes while the numeric keyboard still shows up

### Steps to reproduce
1. grades
2. cga goal seek
3. input number
4. click ok
5. click ok

### Version
ios4.12(26) iphone6

**Comment by chihimng** [comment]
will be fixed next release
