### ISSUE TITLE
[iOS] no "next exam" card in homepage

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#171]
### Expected behavior
show closest coming exam on a card in homepage
click the card to enter timetable > exam

### Actual behavior
no card in homepage

### Steps to reproduce
have an unfinished exam in timetable

**Comment by chihimng** [comment]
just saw cards in my phone, and found that we have implemented it in July 😂 maybe you havent refresh the table?

https://github.com/tszkanlo/USThing_iOS_New/commit/7b6e48dfe2c7a14d4691b52d4d4fa5029da1b371

**Comment by chihimng** [comment]
![img_7664c8ecbcab-1](https://user-images.githubusercontent.com/11769136/33836381-3d593732-dec4-11e7-9da5-31f741b61346.jpeg)
