### ISSUE TITLE
[iOS] Incorrect Timetable Schedule

### ISSUE THREAD

**Issue by tsznokwong** [USThing/USThing_Master#177]
### Expected behavior
Show timetable normally

### Actual behavior
All classes start at 12:00 and end at 12:20/50 instead of correct time 14:00-17:20/50
Refresh, reinstall does not help

### Steps to reproduce
It begins with that,

**Comment by chihimng** [comment]
@tsznokwong can you pm me the sqlite from simulator for debug? 🤔

**Comment by tsznokwong** [comment]
@chihimng When the device is using 24-hour format, issue occurred. It is fine when 12-hour format

**Comment by chihimng** [comment]
omg good find, fixing now

**Comment by tsznokwong** [comment]
I guess you fix it by accident :joy:
refer: https://stackoverflow.com/questions/40055740/app-crashed-when-device-time-is-in-24-hour-format

**Comment by chihimng** [comment]
@tsznokwong seems working on my phone with latest build, please see if v4.20 fixes this

**Comment by tsznokwong** [comment]
fixed
