### ISSUE TITLE
[Directory] Keyboard is not dismissed after doing searching in directory > people

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#179]
### Expected behavior
keyboard dismissed after clicking 'search'
### Actual behavior
keyboard stays on the screen after clicking 'search' and searching results are loaded
(only happens when doing search for the 1st time after entering the directory page)
### Steps to reproduce
directory>people>search e.g. 'thomas'>click search
### Version
Android 3.17

**Comment by tsznokwong** [comment]
duplicated
