### ISSUE TITLE
[Android] FBS only 55 out of 72 venues can be booked through app?

### ISSUE THREAD

**Issue by christyyeung** [USThing/USThing_Master#18]
### App Version and device
Android

### Expected behavior
All direct booking venues on SAO website can be booked through app

### Actual behavior
Only 55 out of 72 venues are found on the app's facilities list

**Comment by zacharylo** [comment]
Because some facilities cannot be booked by students, like some meeting room.

**Comment by c-samuel** [comment]
We have a filter list in Android to filter out those that students can book, but not sure if the list is updated. To be checked.

**Comment by c-samuel** [comment]
Current filter list that cannot be accessed by users in Android, may need to check if the list is updated or any better way to manage it

"Lawn Area  ", "Common Room (1+2)", "Common Room (All)", "Common Room 1", "Common Room 2", "Common Room 3", "Common Room 7", "Conference Room  ", "Creativity Room  ", "Multi-function Room  ", "Workshop  ", "Common Room  (5+6)", "Common Room  4", "Common Room  5", "Lobby Area (LG 1)", "Multi-purpose Room (LG 1027)", "Multi-purpose Room (LG 1031)", "Multi-purpose Room (LG 4204)"
