### ISSUE TITLE
[iOS] Unable to cancel booking reservation

### ISSUE THREAD

**Issue by tsznokwong** [USThing/USThing_Master#193]
### Expected behavior
Cancellation successful
### Actual behavior
Cancellation failed
### Steps to reproduce
Book a group study room & delete
*Please also add the label iOS or / and Android for the issue

**Comment by tsznokwong** [comment]
Issue Fixed

**Comment by chihimng** [comment]
@tsznokwong which branch did you work on for the fix?

**Comment by tsznokwong** [comment]
tszkanlo/USThing_iOS_New#79

**Comment by chihimng** [comment]
icic, next time please use another brach for fixes 🙏
