### ISSUE TITLE
[Feedback] after cropping screenshot, drawing pen is weird when drawing

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#196]
### Expected behavior
draw clear lines
### Actual behavior
draw blurred lines
### Steps to reproduce
1. bug reporter
2. add screenshot
3. take screenshot
4. crop it
5. use drawing pen

**Comment by tsznokwong** [comment]
Iceboxed due to library issue

**Comment by tsznokwong** [comment]
wont fix due to library issue
