### ISSUE TITLE
[bug reporter][ios] when leaving bug reporter, keyboard dismissal is too slow

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#197]
### Expected behavior
keyboard dismissed before going out
### Actual behavior
keyboard dismissed after going out
### Steps to reproduce
1. bug reporter
2. type sth
3. click cancel in bug reporter / submit the feedback (regardless have screenshot or not)

**Comment by tsznokwong** [comment]
Fixed

**Comment by cindyip** [comment]
Tested
