### ISSUE TITLE
[bug reporter][ios] when cancel taking screenshot, should not go directly back to homepage

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#198]
### Expected behavior
go back to feedback submission page
### Actual behavior
go back to homepage
### Steps to reproduce
1. bug reporter
2. add screenshot
3. click 'x'

**Comment by tsznokwong** [comment]
@cindyip do you mean cancel photo editing?
i.e. 
1. bug reporter
2. add screenshot
3. take screenshot
4. click 'x'

**Comment by tsznokwong** [comment]
Issue fixed

**Comment by cindyip** [comment]
@tsznokwong i mean cancel adding the screenshot after taking it. i still see the issue.. can i test it yet?

**Comment by tsznokwong** [comment]
@cindyip the issue is fixed. It should be able to test in next build
