### ISSUE TITLE
[Feedback] chosen color on color palette enlarged when scrolling the palette

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#200]
### Expected behavior
just scroll the color palette normally
### Actual behavior
chosen color on color palette enlarged when scrolling the palette
### Steps to reproduce
1. bug reporter
2. add screenshot
3. take screenshot
4. use pen / text
5. choose a color
6. scroll the color palette

**Comment by tsznokwong** [comment]
Iceboxed due to library issue

**Comment by tsznokwong** [comment]
wont fix due to library issue
