### ISSUE TITLE
[Feedback]  if crop screenshot > constrain > cancel, it leaves the cropping mode

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#207]
### Expected behavior
close the 'constrain' option list
### Actual behavior
leave the cropping mode
### Steps to reproduce
1. bug reporter
2. add screenshot 
3. take screenshot
4. crop
5. constrain
6. click 'cancel'
### Version
ios 4.20 (34)

**Comment by tsznokwong** [comment]
Crop function disabled currently
