### ISSUE TITLE
[Feedback] if add text>tap the text>move the text, top icons overlapped

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#208]
### Expected behavior
only show 'done' button on top
### Actual behavior
'done' button overlap with 'close' 'crop' 'pen' 'text' button
### Steps to reproduce
1. bug reporter
2. add screenshot
3. add text
4. tap on the text
5. keyboard appears
6. move the text when keyboard is appearing
7. notice the 'close' 'crop' 'pen' 'text' buttons on top suddenly appeared

**Comment by tsznokwong** [comment]
Icebox due to library issue

**Comment by tsznokwong** [comment]
wont fix due to library issue
