### ISSUE TITLE
[timematch] keyboard dismissal is too slow when changing event name

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#209]
### Expected behavior
keyboard dismiss before clicking 'save' or 'cancel'
### Actual behavior
keyboard dismiss after clicking 'save' or 'cancel'
### Steps to reproduce
1. timematch
2. click info in a matching
3. click event name
4. change name and click 'save' or 'cancel'

**Comment by tsznokwong** [comment]
Fixed in Phase 2.1 refer tszkanlo/USThing_iOS_New/#94
