### ISSUE TITLE
[settings][ios] the page is not scrollable in 'About'

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#213]
### Expected behavior
scrollable
### Actual behavior
cant scroll, can't see licenses and user data policy
### Steps to reproduce
settings > about
### Environment
- App Version: 4.20(34)
- Phone Model: iphone6
- OS Version: iOS 10.2.1
- OS Language: chinese

**Comment by chihimng** [comment]
Not a bug. They are not required in-app on iOS platform and is displayed on App Store instead.
