### ISSUE TITLE
[bug edit profile]

### ISSUE THREAD

**Issue by Benker-Leung** [USThing/USThing_Master#218]
### Expected behavior
Change preferred Name and keep that changed name
### Actual behavior
After changing the preferred Name in the edit profile, but if I go back to edit profile again, the preferred Name changed back to my full name.
### Environment
- App Version: 4.20(34)
- Phone Model: iPhone6
- OS Version: 11.2.1
- OS Language: iOS

**Comment by tsznokwong** [comment]
Issue should be fixed, please confirm
