### ISSUE TITLE
[About] Credits layout revamp

### ISSUE THREAD

**Issue by bryanchun** [USThing/USThing_Master#222]
### Expected behavior
Aligned logo and text

### Actual behavior
![img-20180206-wa0002](https://user-images.githubusercontent.com/22416129/36099151-932c4e84-103c-11e8-8ba2-d0b455c9e97b.jpg)
Logo is truncated, title and name misaligned

### Steps to reproduce
Go inside About

### Environment
- App Version:
- Phone Model:
- OS Version:
- OS Language:

**Comment by Camerash** [comment]
Okay can do

**Comment by chihimng** [comment]
@Camerash please assign someone for android

**Comment by chihimng** [comment]
![simulator screen shot - iphone x - 2018-02-16 at 19 49 47](https://user-images.githubusercontent.com/11769136/36306413-959ddb7e-1352-11e8-97d3-1d03ec56261e.png)

**Comment by chihimng** [comment]
Implemented and rolled out
