### ISSUE TITLE
[Booking] [Android] Select End Time

### ISSUE THREAD

**Issue by chyuaim** [USThing/USThing_Master#225]
### Expected behavior
Other non-consecutive timeslots will be grey, consecutive timeslots after 2 hours from start time will be grey (can't be selected as end time)
### Actual behavior
Other non-consecutive timeslots was grayed out, but consecutive timeslots after 1 hour from start time was grayed out instead of 2 hours
### Steps to reproduce
1. Select Booking in the homepage
2. Select any rooms of facilities
3. Click on any available room
4. Click an available time slot with a consecutive time slot afterward
### Environment
- App Version: 3.20
- Phone Model: Oneplus 5T
- OS Version: Android 8.0.0
- OS Language: 繁體中文 (香港)

**Comment by Camerash** [comment]
Fixed in v3.30
