### ISSUE TITLE
[Booking] [Android] Booking Failed

### ISSUE THREAD

**Issue by chyuaim** [USThing/USThing_Master#226]
### Expected behavior
After confirm booking rooms or facilities for available time slots while booking limit is not exceeded, booking success dialog should appear.
### Actual behavior
Booking failed dialog appeared for no reason and tell me to try again.
### Steps to reproduce
1. Select booking in homepage
2. Select a room or facility
3. Select a date that rooms or facilities are available and click search
4. Select an available room or facility
5. Select a time slot and click confirm
6. Confirm booking
### Environment
- App Version: 3.20
- Phone Model: Oneplus 5T
- OS Version: Android 8.0.0
- OS Language: 繁體中文 (香港)

**Comment by chihimng** [comment]
@chyuaim there was an issue with our server, please try again now?

**Comment by chyuaim** [comment]
OK, It's fixed now
