### ISSUE TITLE
[Booking] [Android] Keep Loading Under Booked Reservation

### ISSUE THREAD

**Issue by chyuaim** [USThing/USThing_Master#227]
### Expected behavior
Shows reservations made in USThing and via university library website under booked reservation or show 'No Reservations' if no coming reservations made.
### Actual behavior
Just keep displaying "Just a moment.." for an unreasonable amount of time.
### Steps to reproduce
1. Select Booking in homepage
2. Scroll down to booked reservation
### Environment
- App Version: 3.20
- Phone Model: Oneplus 5T
- OS Version: Android 8.0.0
- OS Language: 繁體中文 (香港)

**Comment by chihimng** [comment]
@chyuaim there was an issue with our server, please try again now?

**Comment by chyuaim** [comment]
OK, It's fixed now
