### ISSUE TITLE
[TimeMatch] Bug when sharing results

### ISSUE THREAD

**Issue by c-samuel** [USThing/USThing_Master#232]
### Expected behavior
Show only `{number} People`

### Actual behavior
Optional(3) People

### Steps to reproduce
1. Match with somebody
2. Share the results
3. The session which is not `All People` e.g. 3 People, would show the name `Optional(3) People` instead of `3 People`

According to @chihimng, this is a bug from iOS
### Environment
- App Version: latest one should have this issue too
- Phone Model:
- OS Version: iOS
- OS Language:

e.g. 
－
All People
Mon Before 11:30AM (3.5 hrs)
Mon 01:30PM - 04:00PM (2.5 hrs)
Mon 04:00PM - 07:00PM (3 hrs)
Mon After 07:00PM (1 hr)
Tue Before 10:30AM (2.5 hrs)
Tue 12:00PM - 01:30PM (1.5 hrs)
Tue 01:30PM - 03:00PM (1.5 hrs)
Tue After 06:00PM (2 hrs)
Wed Before 09:30AM (1.5 hrs)
Wed 11:30AM - 12:00PM (0.5 hr)
Wed 12:00PM - 01:30PM (1.5 hrs)
Wed 01:30PM - 03:00PM (1.5 hrs)
Wed 03:00PM - 05:00PM (2 hrs)
Wed 05:00PM - 06:00PM (1 hr)
Wed After 07:00PM (1 hr)
Thu Before 10:30AM (2.5 hrs)
Thu 12:00PM - 01:30PM (1.5 hrs)
Thu 01:30PM - 03:00PM (1.5 hrs)
Thu After 06:00PM (2 hrs)
Fri Before 09:30AM (1.5 hrs)
Fri 09:30AM - 01:30PM (4 hrs)
Fri 01:30PM - 03:00PM (1.5 hrs)
Fri 03:00PM - 05:00PM (2 hrs)
Fri 05:00PM - 06:00PM (1 hr)
Fri After 07:00PM (1 hr)

#### Optional(3) People
Mon 11:30AM - 12:00PM (0.5 hr)
(omitted)

**Comment by tsznokwong** [comment]
Fixed in Phase 2.1
