### ISSUE TITLE
[ems] [android] in events admin > an event > eye icon, the admin shouldn't be able to click the empty blue bar to join event

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#239]
### Expected behavior
hide the blue bar 
### Actual behavior
the admin can click the blue bar, after confirming to join, the app keeps loading
### Steps to reproduce
events admin > click an event > click eye icon > click blue bar on the bottom
### Environment
- App Version: 3.30dev
- Phone Model:Sony Xperia Tablet
- OS Version:android 6.0.1
- OS Language:chinese

**Comment by Camerash** [comment]
Fixed in tszkanlo/USThing_Android#200, awaiting merge
