### ISSUE TITLE
[iOS][Android] contact email on login page

### ISSUE THREAD

**Issue by christyyeung** [USThing/USThing_Master#24]
### App Version and device
Android

### Expected behavior
Please use "usthing@ust.hk" for contact.  Thanks!

**Comment by tszkanlo** [comment]
fixed on https://github.com/tszkanlo/USThing_Android/commit/b4e8f047111d32a82108ff8f30ea44eed2a64d9c

**Comment by tszkanlo** [comment]
iOS fixed
