### ISSUE TITLE
[ems] [enhancement] when successfully scanned QR code and changed attendance status, show a msg to user

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#240]
### Expected behavior
show 'Attendance recorded' something like that
### Actual behavior
show 'Syncing...'
### Steps to reproduce
events admin > enter an event > scan QR code
### Environment
- App Version: 3.30dev
- Phone Model:Sony Xperia Tablet
- OS Version:android 6.0.1
- OS Language:chinese

**Comment by Camerash** [comment]
Fixed in tszkanlo/USThing_Android#200, added nice animation ✨
