### ISSUE TITLE
[career center] [android] reminder list is always empty 

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#242]
### Expected behavior
reminder list shows reminder set up before
### Actual behavior
empty list
(although reminder card is shown in homepage)
### Steps to reproduce
create a job deadline reminder in career center
### Environment
- App Version: 3.30dev
- Phone Model: sony experia tablet
- OS Version:  android 6.0.1
- OS Language: chinese

**Comment by Camerash** [comment]
Fixed in tszkanlo/USThing_Android#201
