### ISSUE TITLE
[ios] [timematch] after creating timematch and back, shouldn't let user edit the event name

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#249]
### Expected behavior
go back directly to list of timematch events joined
### Actual behavior
go back to 'enter timematch title' and 'enter preferred name' page
### Steps to reproduce
1. timematch
2. create new event
3. type title
4. click create
5. back
### Environment
- App Version: 4.32(149)
- Phone Model:iphone6
- OS Version:10.2.1
- OS Language:Trad Chinese

**Comment by tsznokwong** [comment]
Tested, on device issue, no problem in simulator
