### ISSUE TITLE
[timematch] after remove member, its not immediately updated

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#251]
### Expected behavior
after step 3, show updated no. of ppl
after step 4, immediately remove member in calendar view
### Actual behavior
after step 3, for android, the total number of participants is not reduced by 1 in the member list page, ios doesn't have this problem
after step 4, need to go back to time match list to retrieve updated data
### Steps to reproduce
1. timematch
2. enter a timematch
3. remove a member
4. go back to calendar view of timematch results

### Environment
- App Version:4.32(149)
- Phone Model:iphone6
- OS Version:10.2.1
- OS Language:Trad Chinese

App Version: 3.40dev
Phone Model:Sony Xperia Tablet
OS Version:android 6.0.1
OS Language:chinese

**Comment by Camerash** [comment]
Fixed in tszkanlo/USThing_Android#212
