### ISSUE TITLE
homepage noti feed is not cleared after logout

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#254]
### Expected behavior
homepage noti feed is cleared after logout
### Actual behavior
homepage noti feed is not cleared after logout
### Environment
App Version:4.32(149)
Phone Model:iphone6
OS Version:10.2.1
OS Language:Trad Chinese

App Version: 3.40dev
Phone Model:Sony Xperia Tablet
OS Version:android 6.0.1
OS Language:chinese

**Comment by chihimng** [comment]
iOS: fixed in build 151

**Comment by Camerash** [comment]
Fixed in tszkanlo/USThing_Android#211
