### ISSUE TITLE
[android] [static info] after clicking email / phone, app crashed

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#255]
### Expected behavior
open email with email app / call the phone number
### Actual behavior
app crashes
### Steps to reproduce
1. campus info
2. click an email / phone number
### Environment
- App Version: 3.40dev
- Phone Model:Sony Xperia Tablet
- OS Version:android 6.0.1
- OS Language:chinese

**Comment by Camerash** [comment]
Fixed in tszkanlo/USThing_Android#211
