### ISSUE TITLE
[android] [timematch] when >1 person not available, it is shown as 'missing' instead of 'not available'

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#256]
### Expected behavior
show 'person a, person b not available'
### Actual behavior
show 'person a, person b missing'
e.g. when only 1 person is not available, it shows 'person a not available'
### Steps to reproduce
1. timematch
2. enter a timematch event results in calendar view
3. click on a timeslot where >1 person is not available
### Environment
- App Version: 3.40dev
- Phone Model:Sony Xperia Tablet
- OS Version:android 6.0.1
- OS Language:chinese

**Comment by Camerash** [comment]
Fixed in tszkanlo/USThing_Android#211
