### ISSUE TITLE
[android] [timematch] after applying participant count filter and click refresh, the refreshed results is not filtered

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#257]
### Expected behavior
show filtered refreshed results / change back to default participant count filter
### Actual behavior
show refreshed results with default filter
### Steps to reproduce
1. time match
2. enter a time match event results in calendar view
3. change participant count filter
4. refresh the results
### Environment
App Version: 3.40dev
Phone Model:Sony Xperia Tablet
OS Version:android 6.0.1
OS Language:chinese

**Comment by c-samuel** [comment]
@cindyip I don't quite get this issue, can you provide more example?

**Comment by Camerash** [comment]
I think I reproduced it. It is the bug where filters doesn't get applied upon refresh of the timematch

**Comment by Camerash** [comment]
Fixed in tszkanlo/USThing_Android#212
