### ISSUE TITLE
[ios] [timematch] app crashed when click on event name

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#261]
### Expected behavior
show event name and participant list
### Actual behavior
app crashed
### Steps to reproduce
1. time match
2. click a joined event
3. click event name on the top
### Environment
- App Version: 5.0
- Phone Model: iphone 6
- OS Version: iOS 10.2.1
- OS Language: trad chin

**Comment by tsznokwong** [comment]
@chihimng Issue due to retrieving current user itsc, User.mr_findAll() is empty array pls check

**Comment by chihimng** [comment]
@tsznokwong User model is deprecated and cleared on upgrade, for username plz use `UserUtilities.Profile.username()`

**Comment by chihimng** [comment]
seems forgot to migrate this usage 🙈
