### ISSUE TITLE
[ios][Feedback]No response when tap on an added text in the text mode of feedback

### ISSUE THREAD

**Issue by JorJor1234** [USThing/USThing_Master#265]
### Expected behavior
edit content

### Actual behavior
no response

### Steps to reproduce
1 feedback
2. Take screenshot
3. Enter cropping mode
4. Enter Text mode
5. text some words
6. click the words again

### Environment
- App Version:5.0
- Phone Model:ipad a1893
- OS Version:iOS 11.3
- OS Language:trad

**Comment by tsznokwong** [comment]
Long Press to enter edit mode.
