### ISSUE TITLE
[ios][Homepage][Time table card] Two Time Table Cards appear in Homepage

### ISSUE THREAD

**Issue by suanw** [USThing/USThing_Master#266]
### Expected behavior
>>One time table card only

### Actual behavior
After login, reopen app, directly proceed to homepage

### Steps to reproduce
(After login, reopen app) --> Enter into app -->Homepage

### Environment
- App Version: 5.0
- Phone Model: iPhone 7+
- OS Version: iOS 11.4
- OS Language: trad chin

if you need screenshot, feel free to contact me at slack (suanw)

**Comment by chihimng** [comment]
@suanw fixed on build 172, plz verify and close 🙏

**Comment by suanw** [comment]
Verified. Sorry for late.
