### ISSUE TITLE
[ios] [Career Center] Job application added before version 5.0 display as null in Job Reminders

### ISSUE THREAD

**Issue by JorJor1234** [USThing/USThing_Master#267]
### Expected behavior
NO null card display

### Actual behavior
Null card  shown in Job Reminders
Also can't delete null job card in Career Center

### Steps to reproduce
1. Career Center
2. Job Reminders

### Environment
- App Version:5.0
- Phone Model:ipad a1893
- OS Version:iOS 11.3
- OS Language:trad

**Comment by tsznokwong** [comment]
Duplicated USThing/USThing_Master#245
