### ISSUE TITLE
[iOS][Setting]Change Telephone Number to Null --> "Invalid Telephone number"

### ISSUE THREAD

**Issue by suanw** [USThing/USThing_Master#268]
### Expected behavior
change tel no. to null should be alright?

### Actual behavior
Message "Invalid Telephone number" when changing the phone number

### Steps to reproduce
Setting --> user profile --> change tel no. to null

### Environment
- App Version: 5.0
- Phone Model: iPhone 7+
- OS Version: iOS 11.4
- OS Language: trad chin

if you need screenshot, feel free to contact me at slack (suanw)

**Comment by tsznokwong** [comment]
Allow User to clear telephone without warning
