### ISSUE TITLE
[ios][Timetable] Randomly success/ failed in loading timetable "Failed getting time table"

### ISSUE THREAD

**Issue by suanw** [USThing/USThing_Master#269]
### Expected behavior
Homepage --> Timetable 

### Actual behavior
Homepage --> Timetable --> Msg "Failed getting time table"
Sometimes it works but sometimes failed

### Steps to reproduce
Homepage --> Timetable --> Msg "Failed getting time table"

### Environment
- App Version: 5.0
- Phone Model: iPhone 7+
- OS Version: iOS 11.4
- OS Language: trad chin

if you need screenshot, feel free to contact me at slack (suanw) or Joris Yiu

**Comment by tsznokwong** [comment]
@suanw Issue not found. Pls give more info, or closes issue

**Comment by suanw** [comment]
closed
