### ISSUE TITLE
[ios][Booking] change date error, time error?

### ISSUE THREAD

**Issue by suanw** [USThing/USThing_Master#271]
1) 
Change date to another date(e.g. 10/7/18)--> time column also change(from 00:00 automatically, instead of from now?) --> search result error, cannot show 10/7/18 booking

Date: 2018-07-10
Time: From now(22:00) 
To: End of the date

Search result: current date results

### Steps to reproduce
Booking --> Group Study Rooms --> change date --> search

2)
Choose time from 00:00 to 00:00
Some card appears but cannot access

### Steps to reproduce
Booking --> Group Study Rooms --> change time to 00:00 to 00:00 --> search

### Environment
- App Version: 5.0
- Phone Model: iPhone 7+
- OS Version: iOS 11.4
- OS Language: trad chin

if you need screenshot, feel free to contact me at slack (suanw)

**Comment by tsznokwong** [comment]
@suanw Issue 1 not found, Issue 2 implemented.
Pls give extra info, or check again for issue 1

**Comment by suanw** [comment]
Issue 1 closed.

Issue 2: 
If time from 00:00 to 00:00 --> No available Timeslot
If time from 00:00 to 23:30 --> available Timeslot shows and can access available timeslot
please check whether issue 2 logic is ok

**Comment by tsznokwong** [comment]
Issue 2 fixed by restricting user setting end time before or equal to start time
