### ISSUE TITLE
[ios][Reinstall] login card appears in homepage and two time table card appear

### ISSUE THREAD

**Issue by suanw** [USThing/USThing_Master#272]
### Expected behavior
1) Directly access to homepage
2) no login card appears in Homepage or back to select login page to login again???

### Actual behavior
Directly access to homepage
 -->login card appears and two time table cards appear in homepage

### Steps to reproduce
Del app --> reinstall --> open app 

### Environment
- App Version: 5.0
- Phone Model: iPhone 7+
- OS Version: iOS 11.4
- OS Language: trad chin

if you need screenshot, feel free to contact me at slack (suanw)

**Comment by chihimng** [comment]
is "login" shown on upper right button? and did login ui popup after launch?

**Comment by suanw** [comment]
upper right button: my ITSC
 login ui didn't pop-up

**Comment by chihimng** [comment]
@suanw could you plz see if build 172 fix this? thanks 🙏

**Comment by suanw** [comment]
Situation 1:
If version 4.32 update to 5.0(172)
Login card still appear with itsc name on right hand corner

Situation 2:
del app -> reinstall ver 5.0
It jump to select login page (student staff alumni)
Correct?

**Comment by chihimng** [comment]
found a possible cause, plz try again on next build, sorry for troubles 🙏
