### ISSUE TITLE
[Feedback] after adding text on screenshot, the color palette doesn't dismiss

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#273]
### Expected behavior
color palette dismisses
### Actual behavior
color palette remains
### Steps to reproduce
1. feedback
2. add screenshot
3. type text on screenshot
4. finish adding the text
### Environment
- App Version: 5.0
- Phone Model: iphone6
- OS Version:iOS 10.2.1
- OS Language:trad chin

**Comment by tsznokwong** [comment]
should be

**Comment by tsznokwong** [comment]
Icebox as library issue

**Comment by tsznokwong** [comment]
wont fix due to library issue
