### ISSUE TITLE
[Android v4.0.1][Booking]Share link not work

### ISSUE THREAD

**Issue by JorJor1234** [USThing/USThing_Master#276]
### Expected behavior
Display a download site for people who click the link

### Actual behavior
display 404 Forbidden

### Steps to reproduce
1. Add Booking Card
2. Click share button in the Booking Card
3. Share in the WhatsApp
4. Click the link

### Environment
- App Version: Android v4.0.1
- Phone Model: Galaxy 6
- OS Version: 7
- OS Language: trad  chi

**Comment by Camerash** [comment]
Fixed in tszkanlo/USThing_Android#220
