### ISSUE TITLE
[Android v4.0.1][Enanchement][Settings] Telephone Number column can enter with char

### ISSUE THREAD

**Issue by JorJor1234** [USThing/USThing_Master#278]
### Expected behavior
 Number can enter only

### Actual behavior
Char also can enter

### Steps to reproduce
1 Settings
2 User Profile
3. Click Telephone Number column

### Environment
App Version: Android v4.0.1
Phone Model: Galaxy 6
OS Version:7
OS Language: trad chi

**Comment by Camerash** [comment]
Fixed in tszkanlo/USThing_Android#220
