### ISSUE TITLE
[Android v4.0.1][Feedback] Text color not match with selected color

### ISSUE THREAD

**Issue by JorJor1234** [USThing/USThing_Master#279]
### Expected behavior
Text color is white after selected white in color palette

### Actual behavior
Text color is black

### Steps to reproduce
1. Settings 
2. Feedback
3. Take screenshot
4. Enter Text mode
5. choose white color
6. Click 'Done' to finish adding text

### Environment
App Version: Android v4.0.1
Phone Model: Galaxy 6
OS Version:7
OS Language: trad chi

**Comment by Camerash** [comment]
Fixed in tszkanlo/USThing_Android#220
