### ISSUE TITLE
[iOS] [Android] FBS meeting room list not in order

### ISSUE THREAD

**Issue by christyyeung** [USThing/USThing_Master#28]
### Expected behavior
Meeting Room list not in order due to extra spacing for meeting room 6

### Steps to reproduce

*Please also add the label iOS or / and Android for the issue

**Comment by c-samuel** [comment]
Interesting...I found that it is because the official FBS system Meeting Room 6 html has one extra space 
Copied from the official page: `Meeting Room  6 vs Meeting Room 7`

**Comment by chihimng** [comment]
Maybe we could fix it hard-codely for now and file a bug report to FBS as well?

**Comment by Camerash** [comment]
Yes, this is probably an easy way to handle it for now 👍

**Comment by chihimng** [comment]
I've sent an email to SAO regarding the issue

**Comment by c-samuel** [comment]
SAO will handle it quite slow I guess, and I think it is a minor problem for them, coz normal users just won't notice that... 😂

**Comment by Marco129** [comment]
I would suggest to fix it in server side.
In my opinion, it is not good to have so many hard code things in client side, if server side can fix it and won't break existing clients

**Comment by chihimng** [comment]
I agree, lets tag this as server-related issue then?

**Comment by Marco129** [comment]
Fixed and deployed to server. Thanks!
P.S. Filter list also implemented in server
