### ISSUE TITLE
[Android v4.0.1][Events]Can't back to homepage from 'Events' page

### ISSUE THREAD

**Issue by JorJor1234** [USThing/USThing_Master#281]
### Expected behavior
 back to homepage

### Actual behavior
No reaction after clicking the arrow button

### Steps to reproduce
1. Events
2. Back

### Environment
App Version: Android v4.0.1
Phone Model: Galaxy 6
OS Version:7
OS Language: trad chi

**Comment by Camerash** [comment]
Fixed in tszkanlo/USThing_Android#220
