### ISSUE TITLE
[Homepage] Alumni tab appears after app starts

### ISSUE THREAD

**Issue by mcreng** [USThing/USThing_Master#284]
### Unexpected Behaviour 
An 'Alumni' tab can be seen for a second when the app first starts.
See [here](https://streamable.com/4ox9y) for the video.

### Environment
- App Version: v5.0
- Phone Model: iPhone 8
- OS Version: iOS 11.4.1

Keep up the good work.

**Comment by chihimng** [comment]
this will be handled in #324, closing
