### ISSUE TITLE
[iOS] [Android] Incorrect wording in FBS time slot not available pop-up

### ISSUE THREAD

**Issue by christyyeung** [USThing/USThing_Master#29]
### Expected behavior
'time slot' = two words, not 'timeslot'. pls fix 

### Steps to reproduce

*Please also add the label iOS or / and Android for the issue

**Comment by c-samuel** [comment]
Seems the string "timeslots" displayed is passed by server on error case. Can @Marco129 have a look?

**Comment by Marco129** [comment]
Fixed and deployed to server. Thanks @c-samuel 
tszkanlo/USThing_Server@71f8284719e7e1ccab58bbd62d8a8c2694b1691e

Checked that iOS app didn't use the error message returned from API. Still require fix in client app @tszkanlo 
https://github.com/tszkanlo/USThing_iOS_New/blob/v3.46b3/USThing/FBSTableViewController.m#L124

**Comment by tszkanlo** [comment]
@Marco129 i will fix that in ios v3.4
