### ISSUE TITLE
[android] [grades] cannot enter the grade page, server error

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#296]
### Expected behavior
enter the grade function and let user choose semester to view
### Actual behavior
back to homepage and prompts error 'server error'
### Steps to reproduce
click on 'grades'
### Environment
App Version: v4.0.2dev
Phone Model:Sony Xperia Tablet
OS Version:android 6.0.1
OS Language:chinese

**Comment by Camerash** [comment]
Cannot reproduce...please try again and manually to switch to 2FA duo app to see if there's any request on 2FA

**Comment by cindyip** [comment]
sorry, i forgot to accept 2fa request!! it works now. so sorry :p
