### ISSUE TITLE
[TimeMatch] after creating a new timematch, need to click 'back' twice to back to homepage

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#297]
### Expected behavior
after step 5, page title shows as 'timematch'
after step 6, didn't go back to homepage
### Actual behavior
after step 5, page title shows as 'new timematch'
after step 6, back to hompage
### Steps to reproduce
1. enter timematch
2. create a new timematch
3. after successfully created, should land on the empty result page and it apps would ask you to share the event
4. cancel sharing
5. click back to go back to the event list
6. click back to go back to homepage (which doesn't work)
7. click back again to go back to homepage
### Environment
App Version: ios 5.1 (3)
Phone Model: iphone 6
OS Version:11.4.1
OS Language:trad chin

**Comment by chihimng** [comment]
@tsznokwong are you working on this? if so plz assign yourself 🙏

**Comment by tsznokwong** [comment]
Fixed in refactor/system, not that good practice sor.
I will remove commented code in next commit

**Comment by suanw** [comment]
Review (ios ver5.0.2(195))
1. enter timematch
2. create a new timematch
3. after successfully created, should land on the empty result page and it apps would ask you to share the event
4. cancel sharing
5. click back to go back to the new timematch list (??)
6. click back to go back to timematch list (??)
7. click back again to go back to homepage

**Comment by tsznokwong** [comment]
The fix build has not yet release, sorry.
