### ISSUE TITLE
[iOS][timematch][sharelink] Login Required when accessing the shared link

### ISSUE THREAD

**Issue by suanw** [USThing/USThing_Master#298]
### Expected behavior
Redirect to USThing app for timematch

### Actual behavior
Login Required show up even I logged in
Msg: Login Required Please login first!

### Steps to reproduce
Received link by others --> click --> open in USThing --> error

### Environment
- App Version: 5.0(180)
- Phone Model: iP7+
- OS Version: 11.4.1
- OS Language: Trad chi

**Comment by chihimng** [comment]
dev note: seems we forgot to migrate old data model usage, ref ExternalLinkHandler.m line 86

**Comment by tsznokwong** [comment]
in the old translation branch, I have refactor external link handler and planning to do it in branch refactor/system

**Comment by chihimng** [comment]
let's make a hot fix so it won't break for the time being? 🤔
