### ISSUE TITLE
[Android v2.21] UX improvement: add new view for displaying result in FBS

### ISSUE THREAD

**Issue by christyyeung** [USThing/USThing_Master#30]
### Expected behavior
After successful booking, some kind of confirmation message to recap booking details and buttons for making another booking or leave FBS (which takes user back to main menu)
### Actual behavior
Jumps to main menu right away with a short 'success' message at the bottom.  seems abrupt
### Steps to reproduce

*Please also add the label iOS or / and Android for the issue

**Comment by c-samuel** [comment]
Android current behaviour:
- On click ok: back to home page

![fbs-success-handling](https://cloud.githubusercontent.com/assets/6096534/24041141/10bfab44-0b47-11e7-8d88-999b6dfdd188.png)
