### ISSUE TITLE
[ios][Setting][User Profile] App crashed

### ISSUE THREAD

**Issue by suanw** [USThing/USThing_Master#301]
### Expected behavior
user profile show in page

### Actual behavior
app crashed when click in User Profile (for both student and staff)

### Steps to reproduce
Homepage --> setting --> User Profile

### Environment
- App Version: 5.0.1
- Phone Model: iP7+
- OS Version: ios 11.4.1
- OS Language: Trad Chi

**Comment by chihimng** [comment]
this makes 5.0.1 build 186 unusable, will pull from app review queue

**Comment by chihimng** [comment]
dev note: crash due to `[<UITextField 0x7fecc996fa00> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key placeholderColor.
(null)`

**Comment by tsznokwong** [comment]
trying to fix, possibly due to broken referencing and incorrect datatype in storyboard file, but it doesn't fix

**Comment by tsznokwong** [comment]
Issue fixed
