### ISSUE TITLE
[ios][Career Center][Job cart] No response in deleting job in job cart

### ISSUE THREAD

**Issue by suanw** [USThing/USThing_Master#304]
### Expected behavior
job should be deleted after clicking "Delete"

### Steps to reproduce
"..." --> job cart --> swipe left --> click delete on job --> no response

### Environment
- App Version: 5.0.1
- Phone Model: iP7+
- OS Version: ios 11.4.1
- OS Language: Trad Chi

**Comment by chihimng** [comment]
@suanw not reproducible on my end, could be network issue, please try again?

**Comment by suanw** [comment]
tried in ver5.0.1(187). Works normal, maybe my networking issues only /.\
