### ISSUE TITLE
[Android]New version prompt display error

### ISSUE THREAD

**Issue by Camerash** [USThing/USThing_Master#31]
### Expected behavior
When a new version is available, display prompt with clear message to ask the user whether to upgrade or not, and if yes, bring them to google play
### Actual behavior
Everything works fine except the prompt, which has display error as shown below
### Steps to reproduce
Try open up an older version of USThing when a newer version is available

![screenshot_2017-03-15-12-01-44](https://cloud.githubusercontent.com/assets/22164439/23933215/e281d6c4-0977-11e7-9875-52af8c32423f.png)

**Comment by Marco129** [comment]
Additional information:
Only occur in API23 or above
