### ISSUE TITLE
[TimeTable] Custom colour for timetable blocks

### ISSUE THREAD

**Issue by albertlau128** [USThing/USThing_Master#331]
Recommended label: Enhancement / iOS / Android / UI
To enhance readability: Feature for users to modify color of course block and course name (may auto-designate font color to be black/white) in timetable view with color palette/RGB code.

For instance: COMP3111 is hardly readable
![whatsapp image 2018-12-28 at 20 32 09](https://user-images.githubusercontent.com/32214383/50515490-025b4a00-0ae0-11e9-96f9-5fc355edd8a3.jpeg)

**Comment by tsznokwong** [comment]
patches made v5.2.3/v4.2.3
