### ISSUE TITLE
Unexpected behavior when refreshing the individual semester grade page.

### ISSUE THREAD

**Issue by danvim** [USThing/USThing_Master#342]
### Expected behavior

Current semester page should remain in that semester after refreshing.

### Actual behavior

Changed current page to the newest semester not shown before in the semester list.

### Steps to reproduce

1. When semester list isn't refreshed. Enter latest semester.
2. Refresh page
3. Shows updated result of that page.

## I think this is what is happening

Below is an analogy in Vue of what I think is happening.

```jsx
<SemesterGradePage :semester="semesters[currentIndex]"/>

...

onRefresh(){
  $.get(...).done(d => {
    this.semesters.splice();
    d.forEach(t => this.semesters.push(t);
  });
}

```

But in fact, I think it should be:

```jsx
<SemesterGradePage :semester="getSemester(currentSemesterName)"/>
```

### Environment
- App Version: 4.1.1
- OS Version: Android

**Comment by tsznokwong** [comment]
new semester grade page released
