### ISSUE TITLE
[Android] [iOS] Settings for Notifications: button is obstructed by text

### ISSUE THREAD

**Issue by christyyeung** [USThing/USThing_Master#38]
### Actual behavior
"Notifications for New Job Posts" is taking up almost the entire line, only half the button for turning on/off the notification is displayed.
Maybe separate the lines like iOS version:
Notifications for:
New Job Posts [on/off button]
Next Lesson [on/off button]
 
### Steps to reproduce

*Please also add the label iOS or / and Android for the issue

**Comment by c-samuel** [comment]
@christyyeung @chihimng Seems iOS version also has this problem?

![photo6251003279748212656](https://cloud.githubusercontent.com/assets/6096534/24331465/96d8b672-1267-11e7-9849-7e4d80c32002.jpg)

**Comment by chihimng** [comment]
@c-samuel Seems fine on 7 Plus... will check the auto layout settings, which phone are you using?

![img_3859](https://cloud.githubusercontent.com/assets/11769136/24331517/6efcbc4c-1268-11e7-9d5f-e9e792c99c22.PNG)

**Comment by c-samuel** [comment]
@chihimng iPhone 5s...
So we can either change the text to a auto-width text or group these two options to a "notifications" section. which one do u prefer?

**Comment by chihimng** [comment]
Considering that some features we are developing will be sending notifications, better if we have a section to group them up?

**Comment by c-samuel** [comment]
sure, will do it in next release

**Comment by chihimng** [comment]
Something like this?
![simulator screen shot 26 mar 2017 11 39 27 pm](https://cloud.githubusercontent.com/assets/11769136/24332675/80a416f6-127d-11e7-9aa5-953398aa5d93.png)

**Comment by c-samuel** [comment]
Yes for notifications, but seems the user profile one look a bit duplicate 😂

**Comment by chihimng** [comment]
true😂 I'll keep the one for noti only

**Comment by chihimng** [comment]
Fixed
