### ISSUE TITLE
[Android] Career Center: cannot display new results after resetting filters a few times

### ISSUE THREAD

**Issue by christyyeung** [USThing/USThing_Master#39]
### Actual behavior
After a few different searches and resetting filters, the page does not reload (but the loading icon appears and does not go away), same problem persists until exiting app and reopening it

### Steps to reproduce

*Please also add the label iOS or / and Android for the issue

**Comment by c-samuel** [comment]
My current step to repeat the issue:
1. Press search icon, enter some text and search
2. Hide the search bar by pressing search icon again
3. Set some filter
