### ISSUE TITLE
[Android] Common Core Search top right menu no use

### ISSUE THREAD

**Issue by christyyeung** [USThing/USThing_Master#5]
### App Version and device 
Android

### Expected behavior

Menu on top right corner has actual functions for selection (e.g., "start new search", "display last search results")

### Actual behavior

Menu on top right corner has no actual function

**Comment by tszkanlo** [comment]
Fixed by https://github.com/tszkanlo/USThing_Server/commit/eeac3a744388e2f13400b613c8e0cea9319b8cf4
