### ISSUE TITLE
[iOS] Chatroom cannot send message

### ISSUE THREAD

**Issue by chihimng** [USThing/USThing_Master#50]
### Expected behavior
- send button is shown
### Actual behavior
- send button not shown
### Steps to reproduce
- click usthings button
- no send button is present in ui

**Comment by chihimng** [comment]
seems working on 7 and 7+ simulator 🤔
@tszkanlo can you build locally and check again?

**Comment by tszkanlo** [comment]
@chihimng seems working on 6 and 6+ simulator on iOS 9 and 10
and also work on real device

**Comment by chihimng** [comment]
so maybe just a build problem?
