### ISSUE TITLE
[Server] Student Center API may break on and after 10 Apr 2017

### ISSUE THREAD

**Issue by Marco129** [USThing/USThing_Master#54]
Stated on the student center login page http://arr.ust.hk/student-center/
> This login page will be revamped with more user friendly interface.
The change will take effect on 10 Apr 2017. Click here to preview.

Server script may require changes to fit the new layout

**Comment by Marco129** [comment]
tszkanlo/USThing_Server@d0fb879ea67c129a47a56914144e215b7cba9b26 should fix the problem
Total downtime: ~33hours

**Comment by tszkanlo** [comment]
🙏
