### ISSUE TITLE
[Feature Request] Show exam schedule in time table

### ISSUE THREAD

**Issue by chihimng** [USThing/USThing_Master#55]
get exam schedule from sis and display in timetable button, possibly add notification as well

**Comment by Marco129** [comment]
Student Center API updated with exam timetable.
Usage: `?action=exam`
Please let me know if there is anything missing in the API response.
Thanks

**Comment by chihimng** [comment]
response seems fine, thanks

**Comment by chihimng** [comment]
iOS screenshot:
![simulator screen shot 4 apr 2017 12 42 15 am](https://cloud.githubusercontent.com/assets/11769136/24620649/050400f6-18d1-11e7-83a7-34281093b1f6.png)
UI assets:
Tab icon: (not sure if useful for android or not)
https://drive.google.com/open?id=0Bz-6AJW7rg3WWWNudjFBaUZ2MEE
table view cells: reused old ones
