### ISSUE TITLE
Timetable function does not start with Mon when entering the function / refreshing

### ISSUE THREAD

**Issue by c-samuel** [USThing/USThing_Master#58]
### Actual behavior
Will scroll to the Tue timetable (not my class)
![image](https://cloud.githubusercontent.com/assets/6096534/24657256/1e4e87a0-1978-11e7-9ccf-0da80e9af76b.png)

### Steps to reproduce
1. enter the timetable button
2. or after entering, refresh the timetable by pull to refresh or the refresh menu icon

**Comment by Marco129** [comment]
I guess Peter did this for UX.
If you have a very long timetable and today is Friday, you may not want to scroll to the bottom every time you view it.

**Comment by c-samuel** [comment]
That's true ge...but starting with Tue does not help much actually like in this case. I would think it is a bug rather than an user-friendly feature 🙈
then need to think think how to make it look more user-friendly
