### ISSUE TITLE
[iOS] About Page revamp and add new members name

### ISSUE THREAD

**Issue by tszkanlo** [USThing/USThing_Master#59]
Current iOS About page is an image, maybe we need to have to revamp it and use native ui element. And add the new contributed developer names. @chihimng please add your name haha.

**Comment by chihimng** [comment]
ok 😂

**Comment by chihimng** [comment]
actually we can host a full contributor list on master repo / website, and display names of content team members as well? like a record of features/working groups and related members?

**Comment by tszkanlo** [comment]
sure we can haha 😉

**Comment by chihimng** [comment]
screenshot
![simulator screen shot 6 apr 2017 12 42 32 am](https://cloud.githubusercontent.com/assets/11769136/24716546/fc8015e0-1a61-11e7-90c3-829bd4da7d67.png)

**Comment by tszkanlo** [comment]
👍
