### ISSUE TITLE
Student Centre api cannot return timetable

### ISSUE THREAD

**Issue by chihimng** [USThing/USThing_Master#81]
### Expected behavior
return timetable array
### Actual behavior
- empty response in timetable step, 200 status returned, no error found in server log
- problem occurs in both ust and outside network
- problem occurs on iOS with different acc (Elliot, Kelvin)
- problem occurs on Android during first login to app, fixed by refreshing manually (Esmond)
### Steps to reproduce

*Please also add the label iOS or / and Android for the issue

**Comment by Marco129** [comment]
Can't reproduce on Android (current master) & iOS (TestFlight 3.60-15) using @tszkanlo account
Please clear all data then reinstall the app and provide the steps from opening the app
It would be good if you can provide the sequence of issuing request to server (not only student center api)
Thanks

**Comment by Marco129** [comment]
I looked back in Slack, seems Android only have problem on grade but not timetable?
tszkanlo/USThing_Server@eae578a should fix the grade issue

I don't know whether it also affect the timetable
Please try again if you encountered problem on timetable or grade, thanks!

**Comment by chihimng** [comment]
request sequence (from login, sorted by time desc):
![simulator screen shot 26 apr 2017 4 08 30 pm](https://cloud.githubusercontent.com/assets/11769136/25424416/dd852d44-2a9a-11e7-95d4-79f520df01b7.png)

login response:
![simulator screen shot 26 apr 2017 4 09 47 pm](https://cloud.githubusercontent.com/assets/11769136/25424458/f779f25c-2a9a-11e7-9a76-795da79c41a3.png)

timetable response:
![simulator screen shot 26 apr 2017 4 09 07 pm](https://cloud.githubusercontent.com/assets/11769136/25424469/ffdb0a1c-2a9a-11e7-9ffe-4bbdef752891.png)

exam response:
![simulator screen shot 26 apr 2017 4 09 17 pm](https://cloud.githubusercontent.com/assets/11769136/25424483/0d10c8f2-2a9b-11e7-9118-e4302b241336.png)

logout response:
![simulator screen shot 26 apr 2017 4 09 33 pm](https://cloud.githubusercontent.com/assets/11769136/25424492/14e6570e-2a9b-11e7-80ae-2e724407c41b.png)

**Comment by chihimng** [comment]
refresh sequence:
![simulator screen shot 26 apr 2017 4 14 07 pm](https://cloud.githubusercontent.com/assets/11769136/25424596/68f70794-2a9b-11e7-8be6-65391720df3b.png)

response same as above

**Comment by chihimng** [comment]
@Marco129 I can pm you my acc if needed

**Comment by tszkanlo** [comment]
I think this issue may related to the account 🙈
