### ISSUE TITLE
[Library Room Booking] Add table view of all time slots on top of "book given a time slot"

### ISSUE THREAD

**Issue by c-samuel** [USThing/USThing_Master#84]
Displaying the library.ust.hk room booking table, but on a more mobile friendly way perhaps

_*Originally initialized by @bryanchun in android repo, moved to here for easier management._

**Comment by chihimng** [comment]
Similar to issue #36, maybe I'll move those here as well...

And library system will be revamped in around June, so maybe we can discuss user flow and ui first

**Comment by chihimng** [comment]
so turns out library is revamping their catalog system, not booking system, so no effects on us at all...

**Comment by chihimng** [comment]
will be handled in Booking Revamp
