### ISSUE TITLE
[Android] TimeMatch - nothing happened when clicked on link attached to shared text 

### ISSUE THREAD

**Issue by christyyeung** [USThing/USThing_Master#85]
### Expected behavior
Display match results

### Actual behavior
Link appears below shared text, when clicked on it, browser is opened but only a blank page appears (URL: https://www.usthing.xyz/timetable-matching/d6542485) 

### Steps to reproduce

*Please also add the label iOS or / and Android for the issue

**Comment by c-samuel** [comment]
@chihimng has opened up a new issue for this, will close this now
https://github.com/USThing/USThing_Master/issues/88
