### ISSUE TITLE
[TTM] [Server] add landing page for desktop and mobile without app installed

### ISSUE THREAD

**Issue by chihimng** [USThing/USThing_Master#88]
- qr code for joining event
- app download link (and remove iOS App Store code to solve issue with overlapping pop ups)

**Comment by Marco129** [comment]
Links about App Banner that might help for UX:
Android: https://developers.google.com/web/fundamentals/engage-and-retain/app-install-banners/#native_app_install_banners
iOS: https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html

**Comment by IniZio** [comment]
Added both, but it seems either wrong setup or due to the restriction that app install banner only appears when user revisit the site twice on different days within two weeks, I cannot see the app install banner on android. Therefore setting a redirect url to google play instead for now

**Comment by chihimng** [comment]
@IniZio did we finish and deploy this? if so maybe close this issue...
