### ISSUE TITLE
Force Update required

### ISSUE THREAD

**Issue by tszkanlo** [USThing/USThing_Master#90]
Currently can let user skip the update dialog

Proposed Change:
Check Restdb table (AppUpdate), Query latest App Store/Play Store version ->

See if force update needed

e.g.

v3.70 is out on App Store, when user open v3.60 -> Check v3.70 is needed to be force updated

**Comment by chihimng** [comment]
also can show changelog to promote new features after update?

**Comment by tszkanlo** [comment]
maybe open another issue?

**Comment by chihimng** [comment]
sure

**Comment by chihimng** [comment]
@tszkanlo so the force update field means that version is required to update right? e.g. on 3.51 found latest is 3.7, and isForceUpdate of 3.51 = true, then prompt user to update and refuse to show home screen?

**Comment by tszkanlo** [comment]
no ar, the other way round
we should check if the latest version should be force updated?
e.g. on each version, found latest is 3.7 and isFOrceUpdate of 3.7 = true, then force update

**Comment by tszkanlo** [comment]
i just put my work on force-update branch, maybe u see see if that makes sense to u?

**Comment by chihimng** [comment]
sor didn't know you were working on this already 😂
but all our future version will be force update? e.g. if 3.7 = true, 3.71=false, then when 3.71 is rolled out old version suddenly could work again?

**Comment by chihimng** [comment]
implemented in 4.0
