### ISSUE TITLE
alert user to approve 2fa

### ISSUE THREAD

**Issue by chihimng** [USThing/USThing_Master#93]
suggested improvement:
- when accessing student centre api, if wait time > threshold e.g. 5 sec, show alert and tell user if they have enabled 2FA, approve our access via Duo app

**Comment by chihimng** [comment]
screenshots

timetable refresh
![simulator screen shot 11 may 2017 2 16 23 am](https://cloud.githubusercontent.com/assets/11769136/25915198/50a1b91a-35f3-11e7-9eca-f43f26d10d79.png)

login screen
![simulator screen shot 11 may 2017 2 36 11 am](https://cloud.githubusercontent.com/assets/11769136/25915199/50a59bde-35f3-11e7-86fb-409678a2757a.png)

**Comment by c-samuel** [comment]
@Marco129 Seems login screen not added 2fa alert?

**Comment by Marco129** [comment]
@c-samuel Some reminder text is added under the login button
(tszkanlo/USThing_Android#86 first screenshot)
